Repository MADA-UMC/MADA-Server, pull requests merged in 2023-09, with the labels that each got.

#76 Update : gitignore 오타 수정
  .gitignore
Labels: update

#78 Refactor : User PageSet, AlarmSet 코드 리팩토링
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: refactor

#79 Feat : 카테고리 종료 기능 추가
  src/main/java/com/umc/mada/category/controller/CategoryController.java
  src/main/java/com/umc/mada/category/domain/Category.java
  src/main/java/com/umc/mada/category/dto/CategoryRequestDto.java
  src/main/java/com/umc/mada/category/dto/CategoryResponseDto.java
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/domain/Todo.java
  src/main/java/com/umc/mada/todo/dto/TodoRequestDto.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
Labels: feat

#80 Fix : User PageSet 오류 수정
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: refactor, fix

#84 Update : 카테고리 종료, 삭제와 투두 종료 RequestDto 관련 수정
  src/main/java/com/umc/mada/calendar/controller/CalendarController.java
  src/main/java/com/umc/mada/calendar/domain/ManyD_dayException.java
  src/main/java/com/umc/mada/calendar/domain/SameCalendarNameExist.java
  src/main/java/com/umc/mada/calendar/dto/CalendarRequestDto.java
  src/main/java/com/umc/mada/calendar/repository/CalendarRepository.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: update

#86 Update : 카테고리 종료, 삭제와 투두 종료 RequestDto 관련 수정
  src/main/java/com/umc/mada/category/dto/CategoryRequestDto.java
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
Labels: update

#88 Update : 카테고리 삭제시 해당 투두도 삭제
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
Labels: update

#91 Remove & Update & Feat: 사용하지 않는 통계 파일 삭제/ 주, 월별 투두 통계 수정/ 카테고리 통계 수정
  .gitignore
  build.gradle
  src/main/java/com/umc/mada/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/mada/auth/service/CustomUserDetailService.java
  src/main/java/com/umc/mada/config/QueryDslConfig.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/domain/DateFrame.java
  src/main/java/com/umc/mada/todo/dto/CategoryStatisticsDto.java
  src/main/java/com/umc/mada/todo/dto/TodoAverageResponseDto.java
  src/main/java/com/umc/mada/todo/dto/TodoStatisticsRequestDto.java
  src/main/java/com/umc/mada/todo/dto/TodoStatisticsResponseDto.java
  src/main/java/com/umc/mada/todo/repository/CategoryStatisticsVO.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/repository/TodoStatisticsVO.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/resources/application.properties
Labels: feat, update

#92 Update : 반복 투두 조회 수정
  src/main/java/com/umc/mada/todo/service/TodoService.java
Labels: update

#93 Style : User 클래스 관련 메소드명 변경
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: style

#94 Style : findUserAlarmSet 변수명 변경
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: style

#96 Style : My 클래스 메소드명 변경
  src/main/java/com/umc/mada/my/controller/MyController.java
  src/main/java/com/umc/mada/my/service/MyService.java
Labels: style

#98 Fix : 주,월별 통계 http 메소드 get에서 post로 수정
  src/main/java/com/umc/mada/user/controller/UserController.java
Labels: fix

#99 Style : User 클래스 메소드명 변경
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: style
