Repository MADA-UMC/MADA-Server, pull requests merged in 2023-08, with the labels that each got.

#18 Feat : File 추가
  build.gradle
  src/main/java/com/umc/mada/MadaApplication.java
  src/main/java/com/umc/mada/calendar/controller/CalendarController.java
  src/main/java/com/umc/mada/calendar/domain/Calendar.java
  src/main/java/com/umc/mada/calendar/dto/CalendarRequestDto.java
  src/main/java/com/umc/mada/calendar/repository/CalendarRepository.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/java/com/umc/mada/category/controller/CategoryController.java
  src/main/java/com/umc/mada/category/domain/Category.java
  src/main/java/com/umc/mada/category/dto/CategoryRequestDto.java
  src/main/java/com/umc/mada/category/dto/CategoryResponseDto.java
  src/main/java/com/umc/mada/category/repository/CategoryRepository.java
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/file/controller/FileController.java
  src/main/java/com/umc/mada/file/domain/File.java
  src/main/java/com/umc/mada/file/dto/FileRequestDto.java
  src/main/java/com/umc/mada/file/dto/FileResponseDto.java
  src/main/java/com/umc/mada/file/repository/FileRepository.java
  src/main/java/com/umc/mada/file/service/FileService.java
  src/main/java/com/umc/mada/global/BaseEntity.java
  src/main/java/com/umc/mada/global/BaseResponseStatus.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/domain/Todo.java
  src/main/java/com/umc/mada/todo/dto/TodoRequestDto.java
  src/main/java/com/umc/mada/todo/dto/TodoResponseDto.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
  src/main/resources/application.properties
Labels: feat

#19 Feat : 커스텀 authorication을 위한 userDetails 추가
  build.gradle
  src/main/java/com/umc/mada/auth/dto/OAuth2Attributes.java
  src/main/java/com/umc/mada/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/mada/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/umc/mada/auth/jwt/JwtTokenProvider.java
  src/main/java/com/umc/mada/auth/service/CustomUserDetailService.java
  src/main/java/com/umc/mada/config/SecurityConfig.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/CusomtUserDetails.java
  src/main/java/com/umc/mada/user/domain/Role.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/exception/UserNotFoundException.java
  src/main/java/com/umc/mada/user/repository/UserRepository.java
  src/main/java/com/umc/mada/user/service/UserService.java
  src/main/resources/application-jwt.properties
  src/main/resources/application.properties
Labels: feat

#21 Test : Test Commit
  src/main/java/com/umc/mada/global/BaseResponse.java
  src/main/java/com/umc/mada/user/controller/UserController.java
Labels: test

#22 Feat : 닉네임 변경, 전체 공지사항 조회 기능 구현
  build.gradle
  src/main/java/com/umc/mada/notice/controller/NoticeController.java
  src/main/java/com/umc/mada/notice/domain/Notice.java
  src/main/java/com/umc/mada/notice/dto/NoticeListResponseDto.java
  src/main/java/com/umc/mada/notice/dto/NoticeResponseDto.java
  src/main/java/com/umc/mada/notice/repository/NoticeRepository.java
  src/main/java/com/umc/mada/notice/service/NoticeService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/dto/NicknameRequestDto.java
  src/main/java/com/umc/mada/user/dto/NicknameResponseDto.java
  src/main/java/com/umc/mada/user/service/UserService.java
  src/main/resources/application-jwt.properties
  src/main/resources/application.properties
Labels: feat

#23 Update : source update
  src/main/resources/application-jwt.properties
  src/main/resources/application.properties
Labels: update

#25 Feat : 로그아웃, 회원탈퇴, custom 캐릭터 아이템 변경, 캐릭터 초기화
  .gitignore
  src/main/java/com/umc/mada/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/mada/auth/service/CustomUserDetailService.java
  src/main/java/com/umc/mada/calendar/controller/CalendarController.java
  src/main/java/com/umc/mada/calendar/domain/Calendar.java
  src/main/java/com/umc/mada/calendar/dto/CalendarRequestDto.java
  src/main/java/com/umc/mada/calendar/dto/CalendarResponseDto.java
  src/main/java/com/umc/mada/calendar/repository/CalendarRepository.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/java/com/umc/mada/calendar/service/CalendarServiceBuilder.java
  src/main/java/com/umc/mada/config/SecurityConfig.java
  src/main/java/com/umc/mada/custom/controller/CustomController.java
  src/main/java/com/umc/mada/custom/domain/Custom.java
  src/main/java/com/umc/mada/custom/domain/CustomItem.java
  src/main/java/com/umc/mada/custom/domain/HaveItem.java
  src/main/java/com/umc/mada/custom/repository/CustomRepository.java
  src/main/java/com/umc/mada/custom/repository/HaveItemRepository.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/CusomtUserDetails.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/service/UserService.java
  src/main/resources/application-jwt.properties
  src/main/resources/application.properties
Labels: feat

#26 Update & Fix : Calendar ALl + a & 오류 수정
  src/main/java/com/umc/mada/calendar/controller/CalendarController.java
  src/main/java/com/umc/mada/calendar/domain/Calendar.java
  src/main/java/com/umc/mada/calendar/dto/CalendarRequestDto.java
  src/main/java/com/umc/mada/calendar/dto/CalendarResponseDto.java
  src/main/java/com/umc/mada/calendar/repository/CalendarRepository.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/resources/application.properties
Labels: feat

#27 Feat : gitignore 설정
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/resources/application-jwt.properties
  src/main/resources/application.properties
Labels: feat

#28 Test : SecurityConfig Refactoring
  src/main/java/com/umc/mada/config/SecurityConfig.java
Labels: test

#29 Refactor : User Dto 패키지 구조 리팩토링
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/dto/UserResponseDto.java
  src/main/java/com/umc/mada/user/dto/nickname/NicknameRequestDto.java
  src/main/java/com/umc/mada/user/dto/nickname/NicknameResponseDto.java
  src/main/java/com/umc/mada/user/dto/user/UserRequestDto.java
  src/main/java/com/umc/mada/user/dto/user/UserResponseDto.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: refactor

#30 커스텀 기능 구현
  src/main/java/com/umc/mada/config/SecurityConfig.java
  src/main/java/com/umc/mada/custom/controller/CustomController.java
  src/main/java/com/umc/mada/custom/domain/CustomItem.java
  src/main/java/com/umc/mada/custom/domain/HaveItem.java
  src/main/java/com/umc/mada/custom/domain/ItemType.java
  src/main/java/com/umc/mada/custom/dto/CharacterItemResponse.java
  src/main/java/com/umc/mada/custom/dto/CustomItemsResponse.java
  src/main/java/com/umc/mada/custom/dto/CustomResponseDto.java
  src/main/java/com/umc/mada/custom/dto/ItemsElementResponse.java
  src/main/java/com/umc/mada/custom/dto/UserCharacterResponse.java
  src/main/java/com/umc/mada/custom/repository/CustomRepository.java
  src/main/java/com/umc/mada/custom/repository/HaveItemRepository.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/file/domain/File.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/repository/UserRepository.java
Labels: feat

#31 Feat : Todo, Timetable, Category Class 수정
  src/main/java/com/umc/mada/category/controller/CategoryController.java
  src/main/java/com/umc/mada/category/domain/Category.java
  src/main/java/com/umc/mada/category/repository/CategoryRepository.java
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/timetable/controller/TimetableController.java
  src/main/java/com/umc/mada/timetable/dto/TimetableRequestDto.java
  src/main/java/com/umc/mada/timetable/dto/TimetableResponseDto.java
  src/main/java/com/umc/mada/timetable/service/TimetableService.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/domain/Repeat.java
  src/main/java/com/umc/mada/todo/domain/RepeatMonth.java
  src/main/java/com/umc/mada/todo/domain/RepeatMonthConverter.java
  src/main/java/com/umc/mada/todo/domain/RepeatWeek.java
  src/main/java/com/umc/mada/todo/domain/Todo.java
  src/main/java/com/umc/mada/todo/dto/TodoRequestDto.java
  src/main/java/com/umc/mada/todo/dto/TodoResponseDto.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
Labels: feat

#32 Feat : 캘린더 구현(lipton꺼 대신 올림)
  src/main/java/com/umc/mada/calendar/controller/CalendarController.java
  src/main/java/com/umc/mada/calendar/domain/Calendar.java
  src/main/java/com/umc/mada/calendar/domain/ManyD_dayException.java
  src/main/java/com/umc/mada/calendar/domain/SameCalendarNameExist.java
  src/main/java/com/umc/mada/calendar/dto/CalendarRequestDto.java
  src/main/java/com/umc/mada/calendar/dto/CalendarResponseDto.java
  src/main/java/com/umc/mada/calendar/repository/CalendarRepository.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/java/com/umc/mada/timetable/controller/TimetableController.java
Labels: feat

#33 Server julia Update
  src/main/java/com/umc/mada/notice/controller/NoticeController.java
  src/main/java/com/umc/mada/saying/controller/SayingController.java
  src/main/java/com/umc/mada/saying/domain/Saying.java
  src/main/java/com/umc/mada/saying/dto/SayingRequestDto.java
  src/main/java/com/umc/mada/saying/dto/SayingResponseDto.java
  src/main/java/com/umc/mada/saying/repository/SayingRepository.java
  src/main/java/com/umc/mada/saying/service/SayingService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: feat

#35 Feat : Docker 서버 배포 구축
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/umc/mada/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/mada/config/S3Config.java
  src/main/java/com/umc/mada/custom/domain/ItemType.java
  src/main/java/com/umc/mada/custom/dto/UserCharacterResponse.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/login/controller/KakaoRestApi.java
  src/main/java/com/umc/mada/login/controller/LoginController.java
  src/main/java/com/umc/mada/login/dto/LoginRequestDto.java
  src/main/java/com/umc/mada/login/dto/LoginResponseDto.java
  src/main/java/com/umc/mada/login/repository/LoginRepository.java
  src/main/java/com/umc/mada/login/service/LoginService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/service/UserService.java
  src/main/resources/application.properties
Labels: feat

#36 Update : 시간표 불러오기에서 캘린더 스펠링 오류 수정
  src/main/java/com/umc/mada/timetable/controller/TimetableController.java
Labels: update

#39 Refactor : 주석 제거
  src/main/java/com/umc/mada/user/controller/UserController.java
Labels: refactor

#40 Update : Todo, Timetable, Category 수정
  src/main/java/com/umc/mada/category/controller/CategoryController.java
  src/main/java/com/umc/mada/category/domain/Category.java
  src/main/java/com/umc/mada/category/dto/CategoryRequestDto.java
  src/main/java/com/umc/mada/category/dto/CategoryResponseDto.java
  src/main/java/com/umc/mada/category/repository/CategoryRepository.java
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/file/dto/FileRequestDto.java
  src/main/java/com/umc/mada/file/dto/FileResponseDto.java
  src/main/java/com/umc/mada/file/service/FileService.java
  src/main/java/com/umc/mada/timetable/controller/TimetableController.java
  src/main/java/com/umc/mada/timetable/domain/Timetable.java
  src/main/java/com/umc/mada/timetable/dto/TimetableRequestDto.java
  src/main/java/com/umc/mada/timetable/dto/TimetableResponseDto.java
  src/main/java/com/umc/mada/timetable/service/TimetableService.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/domain/Todo.java
  src/main/java/com/umc/mada/todo/dto/TodoRequestDto.java
  src/main/java/com/umc/mada/todo/dto/TodoResponseDto.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: update

#41 Feat : Alarm 구현 진행중 ...
  src/main/java/com/umc/mada/MadaApplication.java
  src/main/java/com/umc/mada/saying/controller/SayingController.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/dto/alarm/AlarmSetRequestDto.java
  src/main/java/com/umc/mada/user/dto/alarm/AlarmSetResponseDto.java
  src/main/java/com/umc/mada/user/dto/user/UserRequestDto.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: test

#42 Refactor : 어노테이션 주석 처리
  src/main/java/com/umc/mada/user/dto/alarm/AlarmSetRequestDto.java
Labels: refactor

#43 Update : 화면설정, 구독 여부 기능 수정
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: update

#44 Feat : 프로필 닉네임, 이메일 조회 기능 구현 / Update : Saying mapping 수정
  src/main/java/com/umc/mada/saying/controller/SayingController.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: feat, update

#45 Test : Test Commit
  src/main/java/com/umc/mada/calendar/domain/Calendar.java
  src/main/java/com/umc/mada/calendar/dto/CalendarRequestDto.java
  src/main/java/com/umc/mada/calendar/dto/CalendarResponseDto.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
Labels: test

#46 Test : Test Commit
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
Labels: test

#47 Update : 닉네임 글자 수 제한 변경
  src/main/java/com/umc/mada/user/dto/nickname/NicknameRequestDto.java
Labels: update

#48 Feat : Notice Date 추가 구현
  src/main/java/com/umc/mada/notice/domain/Notice.java
  src/main/java/com/umc/mada/notice/dto/NoticeListResponseDto.java
Labels: feat

#49 Feat : Icon Class 추가, Category, Timetable Class 수정
  src/main/java/com/umc/mada/category/domain/Category.java
  src/main/java/com/umc/mada/category/domain/Icon.java
  src/main/java/com/umc/mada/category/dto/CategoryRequestDto.java
  src/main/java/com/umc/mada/category/dto/CategoryResponseDto.java
  src/main/java/com/umc/mada/category/repository/IconRepository.java
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/timetable/controller/TimetableController.java
Labels: feat

#50 Update : 캘린더 빌더 color 추가
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
Labels: update

#53 Fix : User updatePageSetting 오류 수정
  src/main/java/com/umc/mada/user/domain/User.java
Labels: fix

#54 기능 수정
  src/main/java/com/umc/mada/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/mada/auth/handler/jwt/JwtAuthenticationFilter.java
  src/main/java/com/umc/mada/auth/handler/jwt/JwtTokenProvider.java
  src/main/java/com/umc/mada/config/SecurityConfig.java
  src/main/java/com/umc/mada/custom/controller/CustomController.java
  src/main/java/com/umc/mada/custom/domain/CustomItem.java
  src/main/java/com/umc/mada/custom/dto/CharacterItemResponse.java
  src/main/java/com/umc/mada/custom/dto/ItemsElementResponse.java
  src/main/java/com/umc/mada/custom/repository/CustomRepository.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: update

#55 Feat : User Alarm 설정 기능 구현
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/domain/User.java
  src/main/java/com/umc/mada/user/dto/alarm/AlarmSetRequestDto.java
  src/main/java/com/umc/mada/user/dto/alarm/AlarmSetResponseDto.java
  src/main/java/com/umc/mada/user/dto/user/UserRequestDto.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: feat

#56 Feat : 착용 아이템 변경 시 여러 아이템 변경 가능하도록 수정
  src/main/java/com/umc/mada/custom/controller/CustomController.java
  src/main/java/com/umc/mada/custom/dto/ItemsElementResponse.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
Labels: feat

#57 Feat : User Class 내 기록 확인하기 (day) 추가
  src/main/java/com/umc/mada/category/controller/CategoryController.java
  src/main/java/com/umc/mada/category/service/CategoryService.java
  src/main/java/com/umc/mada/timetable/controller/TimetableController.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/user/controller/UserController.java
Labels: feat

#58 Feat : 반복 투두 조회 추가
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
Labels: feat

#59 Feat : My Class 변경 및 Response 형태 변경 및 값 추가
  src/main/java/com/umc/mada/my/controller/MyController.java
  src/main/java/com/umc/mada/my/domain/My.java
  src/main/java/com/umc/mada/my/dto/MyRequestDto.java
  src/main/java/com/umc/mada/my/dto/MyResponseDto.java
  src/main/java/com/umc/mada/my/repository/MyRepository.java
  src/main/java/com/umc/mada/my/service/MyService.java
  src/main/java/com/umc/mada/saying/controller/SayingController.java
  src/main/java/com/umc/mada/saying/dto/SayingRequestDto.java
  src/main/java/com/umc/mada/saying/dto/SayingResponseDto.java
  src/main/java/com/umc/mada/saying/service/SayingService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: feat

#60 custom 예외처리와 아이템 구매, 아이템 착용 기능 수정
  src/main/java/com/umc/mada/auth/service/CustomUserDetailService.java
  src/main/java/com/umc/mada/custom/controller/CustomController.java
  src/main/java/com/umc/mada/custom/domain/CustomItem.java
  src/main/java/com/umc/mada/custom/domain/HaveItem.java
  src/main/java/com/umc/mada/custom/domain/ItemUnlockCondition.java
  src/main/java/com/umc/mada/custom/dto/CustomItemsResponse.java
  src/main/java/com/umc/mada/custom/dto/ItemsElementResponse.java
  src/main/java/com/umc/mada/custom/dto/UserCharacterResponse.java
  src/main/java/com/umc/mada/custom/repository/CustomRepository.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/exception/BuyOwnedItemException.java
  src/main/java/com/umc/mada/exception/ControllerAdvice.java
  src/main/java/com/umc/mada/exception/ErrorResponse.java
  src/main/java/com/umc/mada/exception/ErrorType.java
  src/main/java/com/umc/mada/exception/NotAllowToWearingException.java
Labels: feat, update

#62 Feat : Todo Average DTO 구현
  src/main/java/com/umc/mada/todo/dto/TodoAverageRequestDto.java
  src/main/java/com/umc/mada/todo/dto/TodoAverageResponseDto.java
Labels: feat

#63 Refactor : Todo Avg 기능 리팩토링 및 수정
  src/main/java/com/umc/mada/exception/ControllerAdvice.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/dto/TodoAverageRequestDto.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
Labels: refactor

#65 Update : 반복 투두 조회 수정
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
Labels: update

#66 Server lipton
  src/main/java/com/umc/mada/calendar/repository/CalendarRepository.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/java/com/umc/mada/todo/dto/TodoAverageResponseDto.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
  src/main/java/com/umc/mada/user/controller/UserController.java
Labels: feat

#67 Feat : 유저의 토글 설정(화면, 알림) 조회 기능 구현
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: feat

#69 Update : 주,월별 통계 수정
  src/main/java/com/umc/mada/custom/controller/CustomController.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/todo/dto/TodoAverageResponseDto.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/user/controller/UserController.java
Labels: update

#70 Update : Timetable 추가시 반복 투두 조회 수정
  src/main/java/com/umc/mada/timetable/controller/TimetableController.java
Labels: update

#71 Comment : 주석 변경
  src/main/java/com/umc/mada/user/controller/UserController.java
  src/main/java/com/umc/mada/user/service/UserService.java
Labels: comment
