Repository MADA-UMC/MADA-Server, pull requests merged in 2024-05, with the labels that each got.

#137 feat: 통계 특정 월의 todo 날짜 조회 및 리스트 조회 오류 수정과 기본값 처리
  src/main/java/com/umc/mada/my/domain/My.java
  src/main/java/com/umc/mada/todo/controller/ChartController.java
  src/main/java/com/umc/mada/todo/dto/StatisticsResponseDto.java
  src/main/java/com/umc/mada/todo/repository/RepeatTodoRepository.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/repository/statistics/DefaultPreviousCategoryStatisticsVO.java
  src/main/java/com/umc/mada/todo/service/ChartService.java
Labels: feat, refactor, fix

#138 feat: 통계 responseDTO에서 비슷한 뜻을 가지는 변수 수정
  .github/workflows/deploy.yml
  src/main/java/com/umc/mada/auth/service/CustomUserDetailService.java
  src/main/java/com/umc/mada/calendar/controller/CalendarController.java
  src/main/java/com/umc/mada/calendar/repository/CalendarRepository.java
  src/main/java/com/umc/mada/calendar/service/CalendarService.java
  src/main/java/com/umc/mada/custom/controller/CustomController.java
  src/main/java/com/umc/mada/custom/domain/CustomItem.java
  src/main/java/com/umc/mada/custom/domain/HaveItem.java
  src/main/java/com/umc/mada/custom/domain/ItemUnlockCondition.java
  src/main/java/com/umc/mada/custom/domain/WearingItem.java
  src/main/java/com/umc/mada/custom/dto/CustomItemsResponse.java
  src/main/java/com/umc/mada/custom/dto/ItemElementResponse.java
  src/main/java/com/umc/mada/custom/dto/ItemsElementResponse.java
  src/main/java/com/umc/mada/custom/repository/CustomRepository.java
  src/main/java/com/umc/mada/custom/repository/HaveItemRepository.java
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/my/domain/My.java
  src/main/java/com/umc/mada/todo/controller/ChartController.java
  src/main/java/com/umc/mada/todo/controller/TodoController.java
  src/main/java/com/umc/mada/todo/dto/AchievementStatisticsDto.java
  src/main/java/com/umc/mada/todo/dto/CategoryStatisticsDto.java
  src/main/java/com/umc/mada/todo/dto/RepeatTodoRequestDto.java
  src/main/java/com/umc/mada/todo/dto/RepeatTodoResponseDto.java
  src/main/java/com/umc/mada/todo/dto/StatisticsResponseDto.java
  src/main/java/com/umc/mada/todo/dto/TodoStatisticsDto.java
  src/main/java/com/umc/mada/todo/repository/ChartRepository.java
  src/main/java/com/umc/mada/todo/repository/RepeatTodoRepository.java
  src/main/java/com/umc/mada/todo/repository/TodoRepository.java
  src/main/java/com/umc/mada/todo/repository/statistics/AchievementRateStatisticsVO.java
  src/main/java/com/umc/mada/todo/repository/statistics/CategoryStatisticsVO.java
  src/main/java/com/umc/mada/todo/repository/statistics/DefaultPreviousCategoryStatisticsVO.java
  src/main/java/com/umc/mada/todo/repository/statistics/MonthlyBarGraphAndRateStatisticsVO.java
  src/main/java/com/umc/mada/todo/repository/statistics/PreviousCategoryStatisticsVO.java
  src/main/java/com/umc/mada/todo/repository/statistics/TodoBarGraphStatisticsVO.java
  src/main/java/com/umc/mada/todo/repository/statistics/WeeklyBarGraphAndRateStatisticsVO.java
  src/main/java/com/umc/mada/todo/service/ChartService.java
  src/main/java/com/umc/mada/todo/service/TodoService.java
  src/test/java/com/umc/mada/CalendarJpaTest.java
Labels: feat

#139 feat: 통계 responseDTO에서 비슷한 뜻을 가지는 변수 수정
  src/main/java/com/umc/mada/custom/service/CustomService.java
  src/main/java/com/umc/mada/todo/dto/StatisticsResponseDto.java
  src/main/java/com/umc/mada/todo/repository/ChartRepository.java
Labels: feat

#142 fix: 로그인 시 회원탈퇴 여부 체크하면서 발생한 오류 해결(회원탈퇴한 유저가 로그인할 때 어떻게 할지 생각해야 함)
  src/main/java/com/umc/mada/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/mada/auth/service/CustomUserDetailService.java
Labels: bug, fix

#143 fix: 로그인 시 회원탈퇴 여부 체크하면서 발생한 오류 해결
  src/main/java/com/umc/mada/auth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umc/mada/auth/service/CustomUserDetailService.java
Labels: bug, fix
